### ISSUE TITLE
NonLazy is not working

### ISSUE THREAD

**Issue by AndersonDev** [modesttree/Zenject#117]
Hi. I have some flat C# classes. They have initialization logic in constructor. This logic should be called after Bind call, on game startup.

However `.NonLazy()` is not working. My workaround is `Resolve<T>()` immediately aster `Bind<T>()`.

Thanks!

**Comment by Mathijs-Bakker** [comment]
It's expected behavior.

Zenject's execution order is as follow:
- First, all dependencies are installed into the DiContainer;
- Then the dependencies are injected.

So nothings gets injected while the installers are still executed. Marking a dependency with ``.NonLazy`` doesn't matter.

So in those cases (like in an installer, tests or whatever class) when you need to resolve a dependency from the DiContainer, you use the Container.Resolve() method.

**Comment by Mortoc** [comment]
So what does `NonLazy` actually do?
