### ISSUE TITLE
Awake and OnEnable running before Construct with DecoratorSceneContext

### ISSUE THREAD

**Issue by nexxogen** [modesttree/Zenject#5]
Hello and glad to have you back! It was starting to become scary. :)

The package in the attachment contains everything to reproduce the bug. Open and run the 'Decorator Scene'.

To quickly describe the problem, there are two scenes, Main and Decorator. Main has a SceneContext while the Decorator has a DecoratorSceneContext. Both of these scenes have MonoBehaviour classes in them (MainSceneMono and DecoratorSceneMono) which expect dependencies from the other scene. The DecoratorSceneMono also has an Awake method which runs the 'SayHello()' method of the Foo class, which is bound in the Main Scene. Upon running the scene, the Awake method of the DecoratorSceneMono executes before the [Inject] Construct() method. Tests with Start() and OnEnable() have shown this execution order:

Awake() -> OnEnable() -> [Inject] Construct() -> Start()

[DecoratorContext.zip](https://github.com/svermeulen/Extenject/files/3108408/DecoratorContext.zip)

**Comment by svermeulen** [comment]
The problem here is that Unity will always fully start the decorator scene before the main scene is started.  And zenject needs to wait for the install phase to fully complete (including the installers in the main scene) before triggering [Inject].  So I'm not sure there's much zenject can do here.

I can think of some potential workarounds though:
- Use Scene Contract Parent Names instead of decorator scenes (though in your case this probably won't help because you can't have scenes reference dependencies inside each other this way like you can with decorators)
- For objects in your decorator scene, do not use Start and Awake for initialization and instead use [Inject]
- Set the objects in decorator scene to be in-active and then call SetActive once injection occurs

**Comment by nexxogen** [comment]
Alright, thank you for the answer. I don't like it when I have to do anything other than providing references inside an [Inject] method, but I guess it can't be helped in this instance.
